// <auto-generated />
using System;
using DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DatabaseContext.Migrations
{
    [DbContext(typeof(SsoDbContext))]
    [Migration("20231106120540_AdicionaAutincrementoNasPKs")]
    partial class AdicionaAutincrementoNasPKs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Models.AppPortifolio", b =>
                {
                    b.Property<long>("AppId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AppId"));

                    b.Property<string>("ApplicationName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("AppId")
                        .HasName("PK__AppPorti__8E2CF7F9661FC2B9");

                    b.ToTable("AppPortifolio", (string)null);
                });

            modelBuilder.Entity("Models.BillModel", b =>
                {
                    b.Property<long>("BillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BillId"));

                    b.Property<string>("Tipo")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasComment("Tipo do meio de pagamento...");

                    b.Property<string>("UrlApi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("UrlAPI");

                    b.HasKey("BillId")
                        .HasName("PK__BillMode__11F2FC6A3A430D14");

                    b.ToTable("BillModel", (string)null);
                });

            modelBuilder.Entity("Models.CityModel", b =>
                {
                    b.Property<long>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CityId"));

                    b.Property<string>("Ibge")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasColumnName("IBGE");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("StateModelStateId")
                        .HasColumnType("bigint")
                        .HasColumnName("StateModel_StateId");

                    b.HasKey("CityId")
                        .HasName("PK__CityMode__F2D21B76EF796D0B");

                    b.HasIndex("StateModelStateId");

                    b.ToTable("CityModel", (string)null);
                });

            modelBuilder.Entity("Models.CountryModel", b =>
                {
                    b.Property<long>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CountryId"));

                    b.Property<string>("Codigo")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Fone")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("Iso")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("ISO");

                    b.Property<string>("Iso3")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("ISO3");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NomeFormal")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("CountryId")
                        .HasName("PK__CountryM__10D1609F98E06333");

                    b.ToTable("CountryModel", (string)null);
                });

            modelBuilder.Entity("Models.EnrollmentModel", b =>
                {
                    b.Property<long>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EnrollmentId"));

                    b.Property<long>("UserModelUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("UserModel_UserId");

                    b.Property<long>("AppPortifolioAppId")
                        .HasColumnType("bigint")
                        .HasColumnName("AppPortifolio_AppId");

                    b.Property<long>("SignatureModelSignatureId")
                        .HasColumnType("bigint")
                        .HasColumnName("SignatureModel_SignatureId");

                    b.HasKey("EnrollmentId", "UserModelUserId")
                        .HasName("PK__Enrollme__37202B96D10BCCAE");

                    b.HasIndex("AppPortifolioAppId");

                    b.HasIndex("SignatureModelSignatureId");

                    b.HasIndex("UserModelUserId");

                    b.ToTable("EnrollmentModel", (string)null);
                });

            modelBuilder.Entity("Models.OrganizationModel", b =>
                {
                    b.Property<long>("OrganizationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("OrganizationId"));

                    b.Property<string>("Cnpj")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("CNPJ");

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<long>("CityModelCityId")
                        .HasColumnType("bigint")
                        .HasColumnName("CityModel_CityId");

                    b.Property<string>("CreditCardNumber")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Cv")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("CV");

                    b.Property<string>("District")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("EmailContact")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NumberAddr")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("Razao")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("OrganizationId", "Cnpj")
                        .HasName("PK__Organiza__807E7679005F241C");

                    b.HasIndex("CityModelCityId");

                    b.ToTable("OrganizationModel", (string)null);
                });

            modelBuilder.Entity("Models.RoleModel", b =>
                {
                    b.Property<long>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RoleId"));

                    b.Property<string>("RoleName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RoleId")
                        .HasName("PK__RoleMode__8AFACE1A7677E852");

                    b.ToTable("RoleModel", (string)null);
                });

            modelBuilder.Entity("Models.SignatureModel", b =>
                {
                    b.Property<long>("SignatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SignatureId"));

                    b.Property<long>("AppId")
                        .HasColumnType("bigint");

                    b.Property<long>("BillModelBillId")
                        .HasColumnType("bigint")
                        .HasColumnName("BillModel_BillId");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("KeySignature")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("OrganizationModelCnpj")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("OrganizationModel_CNPJ");

                    b.Property<long>("OrganizationModelOrganizationId")
                        .HasColumnType("bigint")
                        .HasColumnName("OrganizationModel_OrganizationId");

                    b.HasKey("SignatureId")
                        .HasName("PK__Signatur__3DCA57A9E0E50FD6");

                    b.HasIndex("BillModelBillId");

                    b.HasIndex("OrganizationModelOrganizationId", "OrganizationModelCnpj");

                    b.ToTable("SignatureModel", (string)null);
                });

            modelBuilder.Entity("Models.StateModel", b =>
                {
                    b.Property<long>("StateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("StateId"));

                    b.Property<long>("CountryModelCountryId")
                        .HasColumnType("bigint")
                        .HasColumnName("CountryModel_CountryId");

                    b.Property<string>("Ddd")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("DDD");

                    b.Property<string>("Ibgecode")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasColumnName("IBGECode");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Uf")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("UF");

                    b.HasKey("StateId")
                        .HasName("PK__StateMod__C3BA3B3ADDB287E7");

                    b.HasIndex("CountryModelCountryId");

                    b.ToTable("StateModel", (string)null);
                });

            modelBuilder.Entity("Models.UserLogin", b =>
                {
                    b.Property<long>("UserLoginId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserLoginId"));

                    b.Property<bool?>("AuthenticateResult")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CreateLogin")
                        .HasColumnType("datetime");

                    b.Property<string>("Log")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("LOG");

                    b.Property<DateTime?>("LogTime")
                        .HasColumnType("datetime");

                    b.Property<long>("UserModelUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("UserModel_UserId");

                    b.HasKey("UserLoginId")
                        .HasName("PK__UserLogi__107D568C5EEFC7AD");

                    b.HasIndex("UserModelUserId");

                    b.ToTable("UserLogin", (string)null);
                });

            modelBuilder.Entity("Models.UserModel", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserId"));

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("GivenName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("RoleModelRoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("RoleModel_RoleId");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("UserName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("UserId")
                        .HasName("PK__UserMode__1788CC4C16F1E003");

                    b.HasIndex("RoleModelRoleId");

                    b.ToTable("UserModel", (string)null);
                });

            modelBuilder.Entity("Models.CityModel", b =>
                {
                    b.HasOne("Models.StateModel", "StateModelState")
                        .WithMany("CityModels")
                        .HasForeignKey("StateModelStateId")
                        .IsRequired()
                        .HasConstraintName("FK__CityModel__State__4AB81AF0");

                    b.Navigation("StateModelState");
                });

            modelBuilder.Entity("Models.EnrollmentModel", b =>
                {
                    b.HasOne("Models.AppPortifolio", "AppPortifolioApp")
                        .WithMany("EnrollmentModels")
                        .HasForeignKey("AppPortifolioAppId")
                        .IsRequired()
                        .HasConstraintName("FK__Enrollmen__AppPo__4BAC3F29");

                    b.HasOne("Models.SignatureModel", "SignatureModelSignature")
                        .WithMany("EnrollmentModels")
                        .HasForeignKey("SignatureModelSignatureId")
                        .IsRequired()
                        .HasConstraintName("FK__Enrollmen__Signa__4CA06362");

                    b.HasOne("Models.UserModel", "UserModelUser")
                        .WithMany("EnrollmentModels")
                        .HasForeignKey("UserModelUserId")
                        .IsRequired()
                        .HasConstraintName("FK__Enrollmen__UserM__4D94879B");

                    b.Navigation("AppPortifolioApp");

                    b.Navigation("SignatureModelSignature");

                    b.Navigation("UserModelUser");
                });

            modelBuilder.Entity("Models.OrganizationModel", b =>
                {
                    b.HasOne("Models.CityModel", "CityModelCity")
                        .WithMany("OrganizationModels")
                        .HasForeignKey("CityModelCityId")
                        .IsRequired()
                        .HasConstraintName("FK__Organizat__CityM__4E88ABD4");

                    b.Navigation("CityModelCity");
                });

            modelBuilder.Entity("Models.SignatureModel", b =>
                {
                    b.HasOne("Models.BillModel", "BillModelBill")
                        .WithMany("SignatureModels")
                        .HasForeignKey("BillModelBillId")
                        .IsRequired()
                        .HasConstraintName("FK__Signature__BillM__4F7CD00D");

                    b.HasOne("Models.OrganizationModel", "OrganizationModel")
                        .WithMany("SignatureModels")
                        .HasForeignKey("OrganizationModelOrganizationId", "OrganizationModelCnpj")
                        .IsRequired()
                        .HasConstraintName("FK__SignatureModel__5070F446");

                    b.Navigation("BillModelBill");

                    b.Navigation("OrganizationModel");
                });

            modelBuilder.Entity("Models.StateModel", b =>
                {
                    b.HasOne("Models.CountryModel", "CountryModelCountry")
                        .WithMany("StateModels")
                        .HasForeignKey("CountryModelCountryId")
                        .IsRequired()
                        .HasConstraintName("FK__StateMode__Count__5165187F");

                    b.Navigation("CountryModelCountry");
                });

            modelBuilder.Entity("Models.UserLogin", b =>
                {
                    b.HasOne("Models.UserModel", "UserModelUser")
                        .WithMany("UserLogins")
                        .HasForeignKey("UserModelUserId")
                        .IsRequired()
                        .HasConstraintName("FK__UserLogin__UserM__52593CB8");

                    b.Navigation("UserModelUser");
                });

            modelBuilder.Entity("Models.UserModel", b =>
                {
                    b.HasOne("Models.RoleModel", "RoleModelRole")
                        .WithMany("UserModels")
                        .HasForeignKey("RoleModelRoleId")
                        .IsRequired()
                        .HasConstraintName("FK__UserModel__RoleM__534D60F1");

                    b.Navigation("RoleModelRole");
                });

            modelBuilder.Entity("Models.AppPortifolio", b =>
                {
                    b.Navigation("EnrollmentModels");
                });

            modelBuilder.Entity("Models.BillModel", b =>
                {
                    b.Navigation("SignatureModels");
                });

            modelBuilder.Entity("Models.CityModel", b =>
                {
                    b.Navigation("OrganizationModels");
                });

            modelBuilder.Entity("Models.CountryModel", b =>
                {
                    b.Navigation("StateModels");
                });

            modelBuilder.Entity("Models.OrganizationModel", b =>
                {
                    b.Navigation("SignatureModels");
                });

            modelBuilder.Entity("Models.RoleModel", b =>
                {
                    b.Navigation("UserModels");
                });

            modelBuilder.Entity("Models.SignatureModel", b =>
                {
                    b.Navigation("EnrollmentModels");
                });

            modelBuilder.Entity("Models.StateModel", b =>
                {
                    b.Navigation("CityModels");
                });

            modelBuilder.Entity("Models.UserModel", b =>
                {
                    b.Navigation("EnrollmentModels");

                    b.Navigation("UserLogins");
                });
#pragma warning restore 612, 618
        }
    }
}
