INSERT INTO CountryModel (Name, Codigo, Fone, Iso, Iso3, NomeFormal) VALUES
('Afeganistão', 'AF', '93', 'AF', 'AFG', 'República Islâmica do Afeganistão'),
('África do Sul', 'ZA', '27', 'ZA', 'ZAF', 'República da África do Sul'),
('Albânia', 'AL', '355', 'AL', 'ALB', 'República da Albânia'),
('Alemanha', 'DE', '49', 'DE', 'DEU', 'República Federal da Alemanha'),
('Andorra', 'AD', '376', 'AD', 'AND', 'Principado de Andorra'),
('Angola', 'AO', '244', 'AO', 'AGO', 'República de Angola'),
('Antígua e Barbuda', 'AG', '1-268', 'AG', 'ATG', 'Antígua e Barbuda'),
('Arábia Saudita', 'SA', '966', 'SA', 'SAU', 'Reino da Arábia Saudita'),
('Argélia', 'DZ', '213', 'DZ', 'DZA', 'República Argelina Democrática e Popular'),
('Argentina', 'AR', '54', 'AR', 'ARG', 'República Argentina'),
('Armênia', 'AM', '374', 'AM', 'ARM', 'República da Armênia'),
('Austrália', 'AU', '61', 'AU', 'AUS', 'Comunidade da Austrália'),
('Áustria', 'AT', '43', 'AT', 'AUT', 'República da Áustria'),
('Azerbaijão', 'AZ', '994', 'AZ', 'AZE', 'República do Azerbaijão'),
('Bahamas', 'BS', '1-242', 'BS', 'BHS', 'Comunidade das Bahamas'),
('Bangladesh', 'BD', '880', 'BD', 'BGD', 'República Popular de Bangladesh'),
('Barbados', 'BB', '1-246', 'BB', 'BRB', 'Barbados'),
('Barein', 'BH', '973', 'BH', 'BHR', 'Reino do Barein'),
('Bélgica', 'BE', '32', 'BE', 'BEL', 'Reino da Bélgica'),
('Belize', 'BZ', '501', 'BZ', 'BLZ', 'Belize'),
('Benim', 'BJ', '229', 'BJ', 'BEN', 'República do Benim'),
('Bielorrússia', 'BY', '375', 'BY', 'BLR', 'República da Bielorrússia'),
('Bolívia', 'BO', '591', 'BO', 'BOL', 'Estado Plurinacional da Bolívia'),
('Bósnia e Herzegovina', 'BA', '387', 'BA', 'BIH', 'Bósnia e Herzegovina'),
('Botsuana', 'BW', '267', 'BW', 'BWA', 'República do Botsuana'),
('Brasil', 'BR', '55', 'BR', 'BRA', 'República Federativa do Brasil'),
('Brunei', 'BN', '673', 'BN', 'BRN', 'Nação de Brunei, a Morada da Paz'),
('Bulgária', 'BG', '359', 'BG', 'BGR', 'República da Bulgária'),
('Burkina Faso', 'BF', '226', 'BF', 'BFA', 'Burkina Faso'),
('Burundi', 'BI', '257', 'BI', 'BDI', 'República do Burundi'),
('Butão', 'BT', '975', 'BT', 'BTN', 'Reino do Butão'),
('Cabo Verde', 'CV', '238', 'CV', 'CPV', 'República de Cabo Verde'),
('Camarões', 'CM', '237', 'CM', 'CMR', 'República dos Camarões'),
('Camboja', 'KH', '855', 'KH', 'KHM', 'Reino do Camboja'),
('Canadá', 'CA', '1', 'CA', 'CAN', 'Canadá'),
('Catar', 'QA', '974', 'QA', 'QAT', 'Estado do Catar'),
('Cazaquistão', 'KZ', '7', 'KZ', 'KAZ', 'República do Cazaquistão'),
('Chade', 'TD', '235', 'TD', 'TCD', 'República do Chade'),
('Chile', 'CL', '56', 'CL', 'CHL', 'República do Chile'),
('China', 'CN', '86', 'CN', 'CHN', 'República Popular da China'),
('Chipre', 'CY', '357', 'CY', 'CYP', 'República de Chipre'),
('Cingapura', 'SG', '65', 'SG', 'SGP', 'República de Cingapura'),
('Colômbia', 'CO', '57', 'CO', 'COL', 'República da Colômbia'),
('Comores', 'KM', '269', 'KM', 'COM', 'União das Comores'),
('Congo-Brazzaville', 'CG', '242', 'CG', 'COG', 'República do Congo'),
('Coreia do Norte', 'KP', '850', 'KP', 'PRK', 'República Popular Democrática da Coreia'),
('Coreia do Sul', 'KR', '82', 'KR', 'KOR', 'República da Coreia'),
('Costa do Marfim', 'CI', '225', 'CI', 'CIV', 'República da Costa do Marfim'),
('Costa Rica', 'CR', '506', 'CR', 'CRI', 'República da Costa Rica'),
('Croácia', 'HR', '385', 'HR', 'HRV', 'República da Croácia'),
('Cuba', 'CU', '53', 'CU', 'CUB', 'República de Cuba'),
('Dinamarca', 'DK', '45', 'DK', 'DNK', 'Reino da Dinamarca'),
('Djibouti', 'DJ', '253', 'DJ', 'DJI', 'República do Djibouti'),
('Dominica', 'DM', '1-767', 'DM', 'DMA', 'Comunidade da Dominica'),
('Egito', 'EG', '20', 'EG', 'EGY', 'República Árabe do Egito'),
('El Salvador', 'SV', '503', 'SV', 'SLV', 'República de El Salvador'),
('Emirados Árabes Unidos', 'AE', '971', 'AE', 'ARE', 'Emirados Árabes Unidos'),
('Equador', 'EC', '593', 'EC', 'ECU', 'República do Equador'),
('Eritreia', 'ER', '291', 'ER', 'ERI', 'Estado da Eritreia'),
('Eslováquia', 'SK', '421', 'SK', 'SVK', 'República Eslovaca'),
('Eslovênia', 'SI', '386', 'SI', 'SVN', 'República da Eslovênia'),
('Espanha', 'ES', '34', 'ES', 'ESP', 'Reino da Espanha'),
('Estados Unidos', 'US', '1', 'US', 'USA', 'Estados Unidos da América'),
('Estônia', 'EE', '372', 'EE', 'EST', 'República da Estônia'),
('Etiópia', 'ET', '251', 'ET', 'ETH', 'República Democrática Federal da Etiópia'),
('Fiji', 'FJ', '679', 'FJ', 'FJI', 'República de Fiji'),
('Filipinas', 'PH', '63', 'PH', 'PHL', 'República das Filipinas'),
('Finlândia', 'FI', '358', 'FI', 'FIN', 'República da Finlândia'),
('França', 'FR', '33', 'FR', 'FRA', 'República Francesa'),
('Gabão', 'GA', '241', 'GA', 'GAB', 'República Gabonesa'),
('Gâmbia', 'GM', '220', 'GM', 'GMB', 'República da Gâmbia'),
('Gana', 'GH', '233', 'GH', 'GHA', 'República do Gana'),
('Geórgia', 'GE', '995', 'GE', 'GEO', 'Geórgia'),
('Granada', 'GD', '1-473', 'GD', 'GRD', 'Granada'),
('Grécia', 'GR', '30', 'GR', 'GRC', 'República Helênica'),
('Guatemala', 'GT', '502', 'GT', 'GTM', 'República da Guatemala'),
('Guiana', 'GY', '592', 'GY', 'GUY', 'República Cooperativa da Guiana'),
('Guiné', 'GN', '224', 'GN', 'GIN', 'República da Guiné'),
('Guiné-Bissau', 'GW', '245', 'GW', 'GNB', 'República da Guiné-Bissau'),
('Guiné Equatorial', 'GQ', '240', 'GQ', 'GNQ', 'República da Guiné Equatorial'),
('Haiti', 'HT', '509', 'HT', 'HTI', 'República do Haiti'),
('Holanda', 'NL', '31', 'NL', 'NLD', 'Reino dos Países Baixos'),
('Honduras', 'HN', '504', 'HN', 'HND', 'República de Honduras'),
('Hungria', 'HU', '36', 'HU', 'HUN', 'Hungria'),
('Índia', 'IN', '91', 'IN', 'IND', 'República da Índia'),
('Indonésia', 'ID', '62', 'ID', 'IDN', 'República da Indonésia'),
('Irã', 'IR', '98', 'IR', 'IRN', 'República Islâmica do Irã'),
('Iraque', 'IQ', '964', 'IQ', 'IRQ', 'República do Iraque'),
('Irlanda', 'IE', '353', 'IE', 'IRL', 'República da Irlanda'),
('Islândia', 'IS', '354', 'IS', 'ISL', 'Islândia'),
('Israel', 'IL', '972', 'IL', 'ISR', 'Estado de Israel'),
('Itália', 'IT', '39', 'IT', 'ITA', 'República Italiana'),
('Jamaica', 'JM', '1-876', 'JM', 'JAM', 'Jamaica'),
('Japão', 'JP', '81', 'JP', 'JPN', 'Japão'),
('Jordânia', 'JO', '962', 'JO', 'JOR', 'Reino Hachemita da Jordânia'),
('Kuwait', 'KW', '965', 'KW', 'KWT', 'Estado do Kuwait'),
('Laos', 'LA', '856', 'LA', 'LAO', 'República Democrática Popular do Laos'),
('Lesoto', 'LS', '266', 'LS', 'LSO', 'Reino do Lesoto'),
('Letônia', 'LV', '371', 'LV', 'LVA', 'República da Letônia'),
('Líbano', 'LB', '961', 'LB', 'LBN', 'República Libanesa'),
('Libéria', 'LR', '231', 'LR', 'LBR', 'República da Libéria'),
('Líbia', 'LY', '218', 'LY', 'LBY', 'Estado da Líbia'),
('Liechtenstein', 'LI', '423', 'LI', 'LIE', 'Principado de Liechtenstein'),
('Lituânia', 'LT', '370', 'LT', 'LTU', 'República da Lituânia'),
('Luxemburgo', 'LU', '352', 'LU', 'LUX', 'Grão-Ducado de Luxemburgo'),
('Macedônia do Norte', 'MK', '389', 'MK', 'MKD', 'República da Macedônia do Norte'),
('Madagascar', 'MG', '261', 'MG', 'MDG', 'República de Madagascar'),
('Malásia', 'MY', '60', 'MY', 'MYS', 'Malásia'),
('Malawi', 'MW', '265', 'MW', 'MWI', 'República do Malawi'),
('Maldivas', 'MV', '960', 'MV', 'MDV', 'República das Maldivas'),
('Mali', 'ML', '223', 'ML', 'MLI', 'República do Mali'),
('Malta', 'MT', '356', 'MT', 'MLT', 'República de Malta'),
('Marrocos', 'MA', '212', 'MA', 'MAR', 'Reino de Marrocos'),
('Maurícia', 'MU', '230', 'MU', 'MUS', 'República da Maurícia'),
('Mauritânia', 'MR', '222', 'MR', 'MRT', 'República Islâmica da Mauritânia'),
('México', 'MX', '52', 'MX', 'MEX', 'Estados Unidos Mexicanos'),
('Mianmar', 'MM', '95', 'MM', 'MMR', 'República da União de Mianmar'),
('Micronésia', 'FM', '691', 'FM', 'FSM', 'Estados Federados da Micronésia'),
('Moçambique', 'MZ', '258', 'MZ', 'MOZ', 'República de Moçambique'),
('Moldávia', 'MD', '373', 'MD', 'MDA', 'República da Moldávia'),
('Mônaco', 'MC', '377', 'MC', 'MCO', 'Principado de Mônaco'),
('Mongólia', 'MN', '976', 'MN', 'MNG', 'Mongólia'),
('Montenegro', 'ME', '382', 'ME', 'MNE', 'Montenegro'),
('Namíbia', 'NA', '264', 'NA', 'NAM', 'República da Namíbia'),
('Nauru', 'NR', '674', 'NR', 'NRU', 'República de Nauru'),
('Nepal', 'NP', '977', 'NP', 'NPL', 'República Democrática Federal do Nepal'),
('Nicarágua', 'NI', '505', 'NI', 'NIC', 'República da Nicarágua'),
('Níger', 'NE', '227', 'NE', 'NER', 'República do Níger'),
('Nigéria', 'NG', '234', 'NG', 'NGA', 'República Federal da Nigéria'),
('Noruega', 'NO', '47', 'NO', 'NOR', 'Reino da Noruega'),
('Nova Zelândia', 'NZ', '64', 'NZ', 'NZL', 'Nova Zelândia'),
('Omã', 'OM', '968', 'OM', 'OMN', 'Sultanato de Omã'),
('Países Baixos', 'NL', '31', 'NL', 'NLD', 'Reino dos Países Baixos'),
('Palau', 'PW', '680', 'PW', 'PLW', 'República de Palau'),
('Panamá', 'PA', '507', 'PA', 'PAN', 'República do Panamá'),
('Papua-Nova Guiné', 'PG', '675', 'PG', 'PNG', 'Papua-Nova Guiné'),
('Paquistão', 'PK', '92', 'PK', 'PAK', 'República Islâmica do Paquistão'),
('Paraguai', 'PY', '595', 'PY', 'PRY', 'República do Paraguai'),
('Peru', 'PE', '51', 'PE', 'PER', 'República do Peru'),
('Polônia', 'PL', '48', 'PL', 'POL', 'República da Polônia'),
('Portugal', 'PT', '351', 'PT', 'PRT', 'República Portuguesa'),
('Quênia', 'KE', '254', 'KE', 'KEN', 'República do Quênia'),
('Quirguistão', 'KG', '996', 'KG', 'KGZ', 'República do Quirguistão'),
('Quiribáti', 'KI', '686', 'KI', 'KIR', 'República de Quiribáti'),
('Reino Unido', 'GB', '44', 'GB', 'GBR', 'Reino Unido da Grã-Bretanha e Irlanda do Norte'),
('República Centro-Africana', 'CF', '236', 'CF', 'CAF', 'República Centro-Africana'),
('República Democrática do Congo', 'CD', '243', 'CD', 'COD', 'República Democrática do Congo'),
('República Dominicana', 'DO', '1-809', 'DO', 'DOM', 'República Dominicana'),
('Romênia', 'RO', '40', 'RO', 'ROU', 'Romênia'),
('Ruanda', 'RW', '250', 'RW', 'RWA', 'República de Ruanda'),
('Rússia', 'RU', '7', 'RU', 'RUS', 'Federação Russa'),
('Salomão', 'SB', '677', 'SB', 'SLB', 'Ilhas Salomão'),
('Samoa', 'WS', '685', 'WS', 'WSM', 'Estado Independente de Samoa'),
('Santa Lúcia', 'LC', '1-758', 'LC', 'LCA', 'Santa Lúcia'),
('São Cristóvão e Nevis', 'KN', '1-869', 'KN', 'KNA', 'Federação de São Cristóvão e Nevis'),
('São Marino', 'SM', '378', 'SM', 'SMR', 'República de São Marino'),
('São Tomé e Príncipe', 'ST', '239', 'ST', 'STP', 'República Democrática de São Tomé e Príncipe'),
('São Vicente e Granadinas', 'VC', '1-784', 'VC', 'VCT', 'São Vicente e Granadinas'),
('Seicheles', 'SC', '248', 'SC', 'SYC', 'República das Seicheles'),
('Senegal', 'SN', '221', 'SN', 'SEN', 'República do Senegal'),
('Serra Leoa', 'SL', '232', 'SL', 'SLE', 'República da Serra Leoa'),
('Sérvia', 'RS', '381', 'RS', 'SRB', 'República da Sérvia'),
('Singapura', 'SG', '65', 'SG', 'SGP', 'República de Singapura'),
('Síria', 'SY', '963', 'SY', 'SYR', 'República Árabe Síria'),
('Somália', 'SO', '252', 'SO', 'SOM', 'República Federal da Somália'),
('Sri Lanka', 'LK', '94', 'LK', 'LKA', 'República Democrática Socialista do Sri Lanka'),
('Suazilândia', 'SZ', '268', 'SZ', 'SWZ', 'Reino de Eswatini'),
('Sudão', 'SD', '249', 'SD', 'SDN', 'República do Sudão'),
('Sudão do Sul', 'SS', '211', 'SS', 'SSD', 'República do Sudão do Sul'),
('Suécia', 'SE', '46', 'SE', 'SWE', 'Reino da Suécia'),
('Suíça', 'CH', '41', 'CH', 'CHE', 'Confederação Suíça'),
('Suriname', 'SR', '597', 'SR', 'SUR', 'República do Suriname'),
('Tailândia', 'TH', '66', 'TH', 'THA', 'Reino da Tailândia'),
('Taiwan', 'TW', '886', 'TW', 'TWN', 'Taiwan (República da China)'),
('Tajiquistão', 'TJ', '992', 'TJ', 'TJK', 'República do Tajiquistão'),
('Tanzânia', 'TZ', '255', 'TZ', 'TZA', 'República Unida da Tanzânia'),
('Timor-Leste', 'TL', '670', 'TL', 'TLS', 'República Democrática de Timor-Leste'),
('Togo', 'TG', '228', 'TG', 'TGO', 'República Togolesa'),
('Tonga', 'TO', '676', 'TO', 'TON', 'Reino de Tonga'),
('Trindade e Tobago', 'TT', '1-868', 'TT', 'TTO', 'República de Trindade e Tobago'),
('Tunísia', 'TN', '216', 'TN', 'TUN', 'República Tunisina'),
('Turcomenistão', 'TM', '993', 'TM', 'TKM', 'Turcomenistão'),
('Turquia', 'TR', '90', 'TR', 'TUR', 'República da Turquia'),
('Tuvalu', 'TV', '688', 'TV', 'TUV', 'Tuvalu'),
('Ucrânia', 'UA', '380', 'UA', 'UKR', 'Ucrânia'),
('Uganda', 'UG', '256', 'UG', 'UGA', 'República de Uganda'),
('Uruguai', 'UY', '598', 'UY', 'URY', 'República Oriental do Uruguai'),
('Usbequistão', 'UZ', '998', 'UZ', 'UZB', 'República do Usbequistão'),
('Vanuatu', 'VU', '678', 'VU', 'VUT', 'República de Vanuatu'),
('Vaticano', 'VA', '39-06', 'VA', 'VAT', 'Estado da Cidade do Vaticano'),
('Venezuela', 'VE', '58', 'VE', 'VEN', 'República Bolivariana da Venezuela'),
('Vietnã', 'VN', '84', 'VN', 'VNM', 'República Socialista do Vietnã'),
('Zâmbia', 'ZM', '260', 'ZM', 'ZMB', 'República da Zâmbia'),
('Zimbábue', 'ZW', '263', 'ZW', 'ZWE', 'República do Zimbábue');